2024-03-16 20:23:56,465 ERROR: Exception on /ejercicios [GET]
Traceback (most recent call last):
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 493, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 522, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2024-03-16 20:25:28,783 ERROR: Exception on /ejercicios [GET]
Traceback (most recent call last):
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 493, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 522, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2024-03-16 20:25:40,414 ERROR: Exception on /ejercicios [GET]
Traceback (most recent call last):
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 493, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 522, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2024-03-16 20:29:14,715 ERROR: Exception on /ejercicios [GET]
Traceback (most recent call last):
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 493, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 522, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\blood\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2024-03-16 20:29:54,597 ERROR: Exception on /ejercicios [GET]
Traceback (most recent call last):
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 310, in _decode_jwt_from_request
    locations = config.token_location
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\config.py", line 44, in token_location
    locations = current_app.config["JWT_TOKEN_LOCATION"]
KeyError: 'JWT_TOKEN_LOCATION'
